### ISSUE TITLE
Calling `getNode()` on the ref of an Animated component is no longer necessary

### ISSUE THREAD

**Issue by Ho3ein-Boka** [oblador/react-native-collapsible#347]
Calling `getNode()` on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release. FlatList

**Comment by pistou** [comment]
This should be corrected by #346 .. Any ETA?

**Comment by marcoaras** [comment]
ReactNativeFiberHostComponent: Calling `getNode()` on the ref of an Animated component is no longer necessary. You can now directly use the ref instead. This method will be removed in a future release.

Still continue in last version.

**Comment by jeancarlos2020** [comment]
Solucion [25a7ad2](https://github.com/oblador/react-native-collapsible/pull/346/commits/25a7ad2f3a4a354a9c1172c197cb2915950f9dc2)

![image](https://user-images.githubusercontent.com/6289980/80271538-a29a9200-8686-11ea-8607-77772bf072ec.png)

**Comment by OsamaMukhtar** [comment]
> Solucion [25a7ad2](https://github.com/oblador/react-native-collapsible/pull/346/commits/25a7ad2f3a4a354a9c1172c197cb2915950f9dc2)
> 
> ![image](https://user-images.githubusercontent.com/6289980/80271538-a29a9200-8686-11ea-8607-77772bf072ec.png)

When will this merged please.

**Comment by nashford77** [comment]
+1 this really needs to be merged and corrected.

**Comment by renishghetia** [comment]
+1 Waiting for PR to be merged

**Comment by awkpagong** [comment]
+1 did the maintainer die of corona virus or something?

**Comment by yesterday24** [comment]
Did someone find a solution for this?

**Comment by willcaul** [comment]
@yesterday24 I used [patch-package](https://github.com/ds300/patch-package)  to apply @marcorm's fix #346 to my project while we wait for the fix to be merged into the `react-native-collapsible` repo

**Comment by elpolyglotino** [comment]
same problem here

**Comment by liran** [comment]
Why can't I install version 1.5.3?
![image](https://user-images.githubusercontent.com/22112008/90504441-a4331d00-e183-11ea-9b36-d594b0a2b7ba.png)
![image](https://user-images.githubusercontent.com/22112008/90504508-c5940900-e183-11ea-8f43-f340784c6f12.png)
