### ISSUE TITLE
Accordion auto-collapses when pressing on a child element

### ISSUE THREAD

**Issue by manosim** [oblador/react-native-collapsible#72]
Hi there and thank you for the amazing work with collapsible and vector-icons! I've been using react-native-collapsible for some time and today I upgraded RN to `0.41.1` and react-native-collapsible to `0.8.0`.

It looks like when I press on an element inside the accordion's collapsible content, it tries to collapse that section while it should not. I am attaching a gif that demonstrates the issue. Hope it makes sense - let me know if you would like any further details!

![uee9icagbg](https://cloud.githubusercontent.com/assets/6333409/22629974/f4cb3c32-ebe8-11e6-8337-85d557f85949.gif)

#### Update
- It looks like neither of the if statements in the [`componentWillReceiveProps`](https://github.com/oblador/react-native-collapsible/blob/39bce554b37a9a2a2a416ff3e7b997e90a20c31c/Collapsible.js#L36-L40) are valid so neither of these are making it collapse.

- Had a look on what changed in `0.0.8` and it looks like the issue has to do with the [_handleLayoutChange](https://github.com/oblador/react-native-collapsible/compare/v0.7.0...v0.8.0#diff-1b0bbe8e52cea8cef2fd62dfa7f7374bR137) method. When I click on a child of the collapsible this method is getting called but it does not enter the [long if statement](https://github.com/oblador/react-native-collapsible/compare/v0.7.0...v0.8.0#diff-1b0bbe8e52cea8cef2fd62dfa7f7374bR134) which will prevent it from collapsing.

**Comment by oblador** [comment]
Oh, that doesn't look right. Do you have any example code I can try out?

**Comment by manosim** [comment]
Sure! Here's a quick example repo I created for this case: https://github.com/manosim/AccordionExample

**Comment by cvongrim** [comment]
I am having the same issue on RN 0.41.2 and 0.8.0. @manosim Did you find any temporary solution?

**Comment by Braidio** [comment]
Had this same issue so I'm super interested in what other people have to say. Basically any interactive child component ( in my case, a textarea input ) causes the Accordion to close.

But, I discovered a super hacky way to get this to work...

Just wrap a `<ScrollView>` around your content. It won't work as a ScrollView because when it opens up, the scrollView will have unbounded height. So it works as just a View. But a View wouldn't get the same results. In any case, I'm super embaressed to use this as a fix. Really looking forward to some reasonable solutions.

**Comment by huyhai** [comment]
thank @Braidio

**Comment by Ralica** [comment]
Not Sure if it would help anyone for the Accordion but I had the same problem with the Collapsible.
In my case I made myself a custom component which contained the Collapsible and its collapsed prop was managed by a property 'isCollapsed' declared in the custom component.
Any time an interactive child component was touched the Collapsible would collapse.
**Solution:**
I realized that the collapsed value of my collapsible which was provided only by the custom component's state values was being lost when a layout change occurs. To ensure that there is a value no matter what I set my 'isCollapsed' state by providing an initial parameter to the custom component or back-fall it to false. 
_Some code:_
`constructor(props, context){
    super(props, context)

    this.state = {
      isCollapsed: props.isCollapsed || false
    }
  }`

**Comment by iRoachie** [comment]
Closing this as inactive as there's been no activity for over 30 days. If the problem re-occurs on the latest version of react-native-collapsible then ping me to reopen or create a new issue.

**Comment by nichesoftgh04** [comment]
Inactivity doesn't mean it got solved :)

**Comment by acb** [comment]
@nichesoftgh04 This appears to be fixed in version `0.10.0`.  So in this case it does mean it got solved!

**Comment by AleksandrLeontev** [comment]
Hi all
I use version 1.2.1
So, I have absolutely the same problem like on the GIF above.
Does anybody know what I can do to solve it. OR WHEN authors can solve it?

**Comment by iRoachie** [comment]
@AleksandrLeontev Can you create an example on https://snack.expo.io that reproduces this?

**Comment by AleksandrLeontev** [comment]
@iRoachie It doesn't render anything on "device", but maybe you could provide some advices based just on code. Thanks.
https://snack.expo.io/rkEZPp2jm

**Comment by AleksandrLeontev** [comment]
@iRoachie Looks like the problem solves when I remove View with flex property.

removing this View (<View style={{ flex: 1, flexDirection: 'column', paddingBottom: 5 }}>) in Collapse in `components/presentationals/FilterGroup` prevents "the ocassional" collapse. 
Why would that happen?

**Comment by tanmaybhatt** [comment]
I am also having this issue. In my case, I am using Tabs inside collapsible. Any interaction with the Tabs causes the unexpected collapse. 
It works fine initially when the collapsed props is false. But once you the change its value, it starts behaving awkwardly.

**Comment by FelipeGCastro** [comment]
For me, problem was solved when i set "flex: 0 " for the contents.

**Comment by Kasun-thilina** [comment]
If anyone is still having this issue. remove all the <View> tags from the Collapsable. I had used a Flatlist inside the Collapsable
like below
```
<View>
<Flatlist/>
</View> 

```

**Comment by iita71737** [comment]
I face the same issue on 1.6.0, 
Has anyone else encountered this?

**Comment by FahadMeraj1** [comment]
@Braidio Thanks man it worked like a charm. 😃 🚀

**Comment by WNortier** [comment]
I'm struggling with this issue Nov 2024. Adding ScrollView also has not solved the problem. Running version ^1.6.2.

State changes are collapsing the accordion even though collapsed property is set to false. This bug wasted a lot of my time. The maintainer should fix this.

Any solution or suggestions?

EDIT: **I downgraded to version ^1.6.1 which fixed it for me.** It doesn't have this bug.

**Comment by yusuffisik** [comment]
Sizin yazacağınız koda ben ... hala hata devam ediyor beceriksizler
